# Generated by Django 4.0.4 on 2022-10-28 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FIFACarrierApp', '0002_alter_playersdata_club_joined_alter_playersdata_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playersdata',
            name='club_joined',
            field=models.DateField(blank='False'),
        ),
        migrations.AlterField(
            model_name='playersdata',
            name='dob',
            field=models.DateField(blank='False'),
        ),
    ]
