# Generated by Django 4.0.4 on 2022-10-28 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FIFACarrierApp', '0004_playersdata_club_flag_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playersdata',
            name='club_joined',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='playersdata',
            name='dob',
            field=models.CharField(max_length=100),
        ),
    ]
